const fs = require('fs');
const file = fs.readFileSync('src/data/demos.ts','utf8');
const marker = 'export function getDemoById';
const idx = file.indexOf(marker);
const before = file.substring(0, idx).trimEnd();
const after = file.substring(idx);
const d = require('./new-demos.json');
const lines = d.map(obj => '  ' + JSON.stringify(obj).replace(/"([^"]+)":/g, '$1:'));
const block = '  // --- NEW DEMOS ---\n' + lines.join(',\n') + ',\n';
fs.writeFileSync('src/data/demos.ts', before + '\n\n' + block + '\n' + after + '\n');
console.log('Added ' + d.length + ' demos');
